### ISSUE TITLE
Clarify Documentation around `storage::new_contract`

### ISSUE THREAD

**Issue by ACStone-MTS** [casper-ecosystem/erc20#104]
This ticket accounts for work done to clarify usage of `storage::new_contract` in relation to contract vs package hash.

Relevant information can be found in [this slack conversation.](https://casper-labs-team.slack.com/archives/CDXBCHB6W/p1690516440005549)

**Comment by gRoussac** [comment]
@ACStoneCL Please ask somebody at L1 to look/validate this commit https://github.com/gRoussac/casper-node/commit/93de0c02e71e52e1a60686cb25a343613f20ad60 and I'll open a PR if okay

**Comment by gRoussac** [comment]
@ACStoneCL this is not cep-18 can we move that ticket to casper node please ?

**Comment by ACStone-MTS** [comment]
Issue is not pertinent to `cep18` specifically.
