### ISSUE TITLE
Receiving "Out of gas error" while deploying

### ISSUE THREAD

**Issue by fromanother** [casper-ecosystem/erc20#20]
Been trying to deploy this to testnet and keep getting "Out of gas error"

https://testnet.cspr.live/account/01b202457a136b9acb8a03760797ed2e6c5ee486c367371043369a9a572dc833cb

On Ubuntu 18 LTS
Casper client 1.1.1

Ran the commands:
 
```
git clone https://github.com/casper-ecosystem/erc20 && cd erc20
make prepare
make build-contract
casper-client put-deploy --chain-name casper-test --node-address http://173.249.29.90:7777 --secret-key ./keys/secret_key.pem --session-path ./target/wasm32-unknown-unknown/release/contract.wasm   --payment-amount 3000000000 --session-arg "token_name:string='GAP CSPR-ETH'" --session-arg "token_symbol:string='GAP'" --session-arg "token_decimals:u8='2'"  --session-arg "token_total_supply:u256='100000000'"
```

**Comment by ipopescu** [comment]
@fromanother do you still have this issue? If so, can you check this explanation: https://casper.network/docs/economics/gas-concepts#why-do-i-see-an-out-of-gas-error.
Can we close the card?

**Comment by ipopescu** [comment]
Closing the issue. Please re-open it if it is still happening.
