### ISSUE TITLE
Error unresolved imports 

### ISSUE THREAD

**Issue by vishal33singh** [casper-ecosystem/erc20#36]
error[E0432]: unresolved imports `libc::sysconf`, `libc::_SC_PAGESIZE`

getting this error while make test .

**Comment by ipopescu** [comment]
@vishal33singh could you try again following these instructions: 
- https://casper.network/docs/dapp-dev-guide/getting-started
- https://casper.network/docs/dapp-dev-guide/tutorials/erc20/prepare

**Comment by gachouchani1999** [comment]
try `make_prepare` and `make build-contract`

**Comment by ipopescu** [comment]
Closing this issue. Please see the instructions above. If you still have problems, please feel free to re-open it.
