### ISSUE TITLE
Need to update current erc20 library

### ISSUE THREAD

**Issue by eroist** [casper-ecosystem/erc20#39]
Cargo libraries associated with Casper network were updated a week ago.
for instance, casper-contract 1.4.3 -> 1.4.4, casper-types 1.4.6 -> 1.5.0
But current erc20 library use the old version of casper-contract library.
Is it ok for me to use current erc20 library using updated casper-contract library to develop smart contract?
when I use current erc20 library, I got below error.
![image](https://user-images.githubusercontent.com/97012368/162905615-60f25b58-ab47-403a-ac05-82e2973f68a9.png)
We need to update erc20 library.

**Comment by darthsiroftardis** [comment]
@eroist have you ran `make setup-rs` also update the nightly toolchain if you haven't already
