### ISSUE TITLE
multiple broken links in tutorial README

### ISSUE THREAD

**Issue by jekennedy** [casper-ecosystem/erc20#45]
All of the links in the [tutorial](https://github.com/casper-ecosystem/erc20/blob/master/docs/TUTORIAL.md) that refer to the old docs site (https://casper.network/docs) do not work properly, as they just redirect to the main docs landing page. 

For example, the first one is: [Writing Rust Contracts on Casper](https://casper.network/docs/dapp-dev-guide/writing-contracts/rust/)

I would have fixed these myself but some of the broken links don't have an obvious match in the new docs site.

**Comment by ipopescu** [comment]
This has already been done in recent PRs. Closing the ticket.
