### ISSUE TITLE
Remove legacy commands from the `lib.rs` comments section

### ISSUE THREAD

**Issue by devendran-m** [casper-ecosystem/erc20#49]
Remove the obsolete `cargo casper --erc20 <PATH TO NEW PROJECT>` comment from [this](https://github.com/casper-ecosystem/erc20/blob/79ca64b2037e9b0775c6e1d312b7a4325212a010/erc20/src/lib.rs#L6-L11) comments section of `lib.rs`

**Comment by gRoussac** [comment]
Hi @devendran-m This has been removed on `dev` branch. Closing this for now thanks.

**Comment by devendran-m** [comment]
Thanks, @gRoussac , much appreciated
